<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Copropiedad extends Model
{
    use HasFactory;

    protected $table = 'copropiedades';

    protected $fillable = [
        'nit_copropiedad',
        'nombre_copropiedad',
        'tipo_unidad',
        'torre_bloque',
        'n°',
        'matricula_inmobiliaria',
        'ficha_catastral',
        'area_mt_cuadrado',
        'coeficiente_participacion',
        'propietario1',
        'propietario2',
        'inmobiliaria',
        'arrendatario1',
        'arrendatario2',
        'placa_vehiculo',
        'profesion_oficio',
        'fecha_inicio_cuotaOrdinaria',
        'fecha_final_cuotaOrdinaria',
        'expensa_total_cuotaOrdinaria',
        'incremento_expensas_mes_cuotaOrdinaria',
        'modo_aplicacion_cuotaOrdinaria',
        'fecha_inicio_ordinariaModular',
        'fecha_final_ordinariaModular',
        'expensa_total_ordinariaModular',
        'incremento_expensas_mes_ordinariaModular',
        'modo_aplicacion_ordinariaModular',
        'fecha_inicio_extraordinaria',
        'fecha_final_extraordinaria',
        'expensa_total_extraordinaria',
        'incremento_expensas_mes_extraordinaria',
        'modo_aplicacion_extraordinaria',
        'fecha_inicio_extraordinariaModular',
        'fecha_final_extraordinariaModular',
        'expensa_total_extraordinariaModular',
        'incremento_expensas_mes_extraordinariaModular',
        'modo_aplicacion_extraordinariaModular',
        'codigo_unidad1',
        'nombre_unidad1',
        'coeficiente_unidad1',
        'cuotaOrdinaria_unidad1',
        'ordinariaModular_unidad1',
        'extraordinaria_unidad1',
        'extraordinariaModular_unidad1',
        'fechaInicio_descuentoOrdinaria',
        'fecha_final_descuentoOrdinaria',
        'descuento_porcentaje_ordinaria',
        'valor_fijo_ordinaria',
        'fechaInicio_descuentoOrdinariaModular',
        'fecha_final_descuentoOrdinariaModular',
        'descuento_porcentaje_ordinariaModular',
        'valor_fijo_ordinariaModular',
        'fechaInicio_retroactivoOrdinaria',
        'fechaFinal_retroactivoOrdinaria',
        'nombreUnidad1_retroactivoOrdinaria',
        'valorUnidad1_retroactivoOrdinaria',
        'fechaInicio_retroactivoOrdinariaModular',
        'fechaFinal_retroactivoOrdinariaModular',
        'nombreUnidad1_retroactivoOrdinariaModular',
        'valorUnidad1_retroactivoOrdinariaModular',
        'fechaInicio_consejeroOrdinaria',
        'fechaFinal_consejeroOrdinaria',
        'descuentoOrdinaria_consejero',
        'valorFijo_consejeroOrdinaria',
        'nombreUnidad1_consejeroOrdinaria',
        'propietarioUnidad1_consejeroOrdinaria',
        'valorUnidad1_consejeroOrdinaria',
        'fechaInicio_consejeroOrdinariaModular',
        'fechaFinal_consejeroOrdinariaModular',
        'descuentoOrdinariaModular_consejero',
        'valorFijo_consejeroOrdinariaModular',
        'valorUnidad1_consejeroOrdinariaModular',
        'fechaInicio_conceptoFacturación',
        'fechaFinal_conceptoFacturacion',
        'codigo_conceptoFacturacion',
        'nombre_conceptoFacturacion',
        'valorFijo_conceptoFacturacion',
        'valorImpuesto_IVAGeneradoPorcentaje',
        'valorFijoImpuesto_IVAGenerado',
        'imputacionContable_Db',
        'imputacionContable_Cr',
        'aplicarA_conceptoFacturacion',
        'tasaMensual',
        'logo',
    ];
}
